export default {
  carData: [
    //车辆导出字段
    {'car_num': '车牌号'},
    {'carry_person_num': '核载人数(人)'},
    {'car_type_name': '车辆类型'},
    {'car_emission_grade': '尾气排放标准'},
    {'oil_type': "燃油类型"},
    {'power_type': '车辆动力类型'},
    {'total_weight': '总质量(kg)'},
    {'carry_weight': '核载重量(kg)'},
    {'car_weight': '整车重量(kg)'},
    {'new_date': "生产日期"},
    {'car_size_length': '车辆外观尺寸长(米)'},
    {'car_size_width': '车辆外观尺寸宽(米)'},
    {'car_color': '车辆颜色'},
    {'transport_type_name': '收运类型'},
    {'power_type': '车辆动力类型'},
    // {"plant1": "绑定处理厂1"},
    // {"plant2": "绑定处理厂2"},
    // {'plant3': '绑定处理厂3'},
    // {'plant4': '绑定处理厂4'},
    // {'plant5': '绑定处理厂5'},
    {"mo_plant1": "末端设施1"},
    {"mo_plant2": "末端设施2"},
    {'zhong_plant1': '中转设施1'},
    {'zhong_plant2': '中转设施2'},
    // {'facility_num': '车辆资产编号'},
    {'del_date': '报废日期'},
    // {'facility_status_name': "指标状况"},
    // {'cost': '购置费用(万元)'},
    {'reg_date': '登记日期'},
    {'brand': '品牌型号'},
    {'receive_date': '接管日期'},
    {'run_year': "运营年限(年)"},
    {'contacts': '联系人'},
    {'phone': '联系电话'},
    {'operate_unit': "运营单位"},
    {'manage_unit': '管理单位'},
    {'property_unit': '产权单位'},
    {'is_runing_name': '是否有作业能力'},
    {'is_weight_name': '是否安装计量称重设备'},
    {'is_self_name': '是否涂装'},
    {"is_gps_name": "是否安装gps"},
  ],
  //人员管理导出字段
  personnelData: [
    {'work_name': "人员姓名"},
    {'phone': '联系方式'},
    {'age': "年龄"},
    {'sex': '性别'},
    {'job': '职务'},
  ],
  //资质管理出字段
  certificationData: [
    {'name': '资质名称'},
    {'signed_time': '证书备案日期'},
    {'viald_time': '证书有效期'},
    {'certificate_number': '证书编号'},
    {'licensed_content': '许可内容'},
    {'licence_place': "发证机关"},
  ],
  //合同管理出字段
  contractData: [
    {'con_name': '合同名称'},
    {'con_type_name': '合同类型'},
    {'signed_time': '签订时间'},
    {'con_viald_time': "合同有效期"},
    {'content': "备注"},
  ],
}
